
* Flying
** Recent Incident
On jan 9 outside the palisades fire, SuperScooper Quebec 1 was struck by a civilian drone.
- LACoFD would like to remind everyone that flying a drone in the midst of firefighting efforts is a federal crime and punishable by up to 12 months in prison or a fine up to $75,000.

*** Bird Strikes
Yeah. Watch out. Don't die.

*** Air Force plans to recurit teenage gamers
Hand-eye coordination or something. I don't really know. Good for drones and stuff.

** Flying a UAV
*** UAV Terminology
There are 4 forces of flight that any aircraft will have to deal with
- Lift
- Drag
- Thrust
- Gravity

The terms that are used to describe the 3 axis are the following:
- Yaw
- Pitch
- Roll

Additional Controls:
- Trim - buttons in the remote control to help adjust roll, pitch, yaw
- Rudder - same as the left stuck, but directly coordinates yaw.

Additional forces
- Wind
- Angular Momentum (propellers moving, which causes angular momentum)

Force of gravity: $F_g=mg$, where $g=9.8 \frac{m}{s^2}=32.2\frac{ft}{s^2}$

What happens when all the propellers spin in the same direction?
- It's going to be in a flat spin across the perpindicular axis.
- Perpindicular momentum.

Why is the preferred propeller spin directions?
- Angular momentum still exists, but because the propellers are in different directions, the angular momentum between each of the propellers essentially cancel out.
- Not all propellers are built the same. There could be flaws in one compared to another (despite being made to be almost mirror images.)

*** Wind
Speed direction
- Wind makes control more difficult
- Wind reduces stability
- Wind usually causes battery to be depleted faster

*** Drag
Drag is the aerodynamic force that opposes an aircrafts motion through the air.
- It is a mechanical force
- Generated by interaction and contact of a body with liquid or gas.

Drag force *F_d* always opposes the motion of an object.
- $F_d=\frac{1}{2}C \rho A v^2$
- $C$ is the drag cooeficent
- $A$ is the area of the object facing the fluid
- $\rho$ is the density of the fluid or gas


*** Remote Station
There is some special switches:
- Power light
- Antenna
- Landing gear
- Flaperon
- ...

They can go from ~$150 to ~$1250 depending on which controller you're looking for.

Controls:
- Throttle (up/down), Yaw (left/right)
- Pitch (up/down), Roll (left/right)

Flight Modes:
- Manual (like flying a helicopter)
- Attitude (auto-level)
- GPS Hold (returns to the quadcopters position once the sticks have been centered)

Away vs Towards
- Flying a drone away from you vs toward you, the controls are reversed.
- You need to flip a switch in your mind.


*** Conclusions
Look it up.
