#+TITLE: Introduction to Theory of Automata

Taken from: 
- *Elements of the Theory of Computation* (2nd Edition) by *Harry R. Lewis* and *Christos H. Papadimitriou*.
- *Introduction to the Theory of Computation* by *Michael Sipser*.

** Regarding grading
- No communication with classmates. It will be treated as cheating, which is -5 points for each warning.
- No AI tools allowed.

** Why study automata?
*** What is automata
_Auto_ means *Moving*\n
_Mata_ means *Machine*\n
Therefore, *Moving Machine* or *Functioning Machine*

- Robot, humanoid, computer, android, mechanism
- For an *Algorithm* to execute, it needs a machine to execute it.
- Our most standard and ancient intution on algorithm follows from a calculator. (computing automataon)
  - Abbacus, Cash register, etc.

*** What is an algorithm.
- The *automata* is the chef/cook.
- The *algorithm* would be the recipe.

For cheesecake, for example, you need to follow certain steps. Cream cheese, sugar, etc.\n
You cannot make a cheesecake without someone/something to cook it. You cannot grow cheesecake.\n

Each instruction is expressed by a finite number of symbols.\n
If it is carried without error, it produces the same result.\n
Whenever you design an algorithm, it is like designing a virtual machine.\n
Exploring the possibilities of algorithms is like exploring the possibilities of machines.
