

* Ordered Pairs
$(x,y)$ is an ordered pair.
$x,y$ are called components (of the ordered pair.)
Order matters:
- $(x,y)\not=(y,x)$

** Cartesian product
Definition:
- $A\times B = \{(x,y):x\in A \text{ and } y \in B\}$
- $\{a,b\}\times\{c,d\}=\{(a,c),(a,d),(b,c),(b,d)\}$



$2^{\{a\}}\times 2^{\{b\}} = \text{?}$

$\{\emptyset,\{a\}\}\times\{\emptyset,\{b\}\}=\{(\emptyset,\emptyset),(\emptyset,\{b\}),(\{a\},\emptyset),(\{a\},\{b\})\}$


Visual:
\begin{matrix}
{ } & c & d\\
a & ac & ad\\
b & bc & bd
\end{matrix}

** Ordered Tuple
Definition:
- $(a_1,a_2,a_3,...,a_n)$ is an ordered n-tuple
- Each $a_i$ is called the i'th component of the ordered tuple.
- The ordered 2-tuple is ordered pair.

A relation $R$ is a set of ordered pairs.
- Attendence sheet produces a relation $\{(\text{Alice},X),(\text{Bob},\text{-})...\}$

* Functions
Definition:
- A function is a special kind of relation (all functions are relations, but not all relations are functions.)
- A relation $R\subset A\times B$ is a function if: For each $a \subset A$, there is exactly one ordered pair in $R$ with the first component $a$.

Example:
- $R_1=\{(x,y):x\in C,y\in S, \text{x is a city in state y}\}$
- $R_2=\{(x,y):x\in S,y\in C, \text{y is a city in state x}\}$
- Which one is a function?
- The first one! Not the second.

A function $f$ that is a subset of $A \times B$ is written as:
- $f: A \to B$

$(a,b) \in f$ is written as $f(a)=b$

$A$ is the domain of the function
- if $A' \subseteq A, f(A')=\{b:f(a)=b\text{ for some } a \in A'\}$ is the image of $A'$
- the range of a function is the image of its domain.

A function $f: A \to B$ is:
- *one-to-one*, if no elements in $A$ match to the same element in $B$.
- *onto*, if each element in $B$ is mapped to by at least one element in $A$.
- *bijection*, if it is both one-to-one and onto.

The inverse of a binary relation $R \subseteq A \times B$ is $\{(b,a): (a,b) \in R\}$ and denoted as $R^{-1}$
The inverse of a relation, which is not a function, can be a function.

* Graphs
Relation graph:
- Representing a relation $R \subseteq A\times A$ using a *directed graph*
- Use nodes to represent elements
- Use directed edge to represent an ordered pair.
- $R=\{(a,b),(b,c),(c,d),(d,e)\}$ can essentially be transformed into a diagram.

** Relations
A relation $R\subseteq A\times A$ is *reflexive* if:
- $(a,a)\exists R$ for every $a \in A$
- Equivalently, every node has a self-loop.

A relation $R\subseteq A\times A$ is *symmetric* if:
- $(a,b)\in R$ or $(b,a) \in R$
- Equivalently, every edge between two nodes is "two-ways"

A relation $R\subseteq A\times A$ is *antisymmetric* if:
- $(a,b)\in R$ and $a \not= b$, then $(b,a)\not\in R$
- Equivalently, every edge between two different nodes is "one-way"

A relation $R\subseteq A\times A$ is *transitive* if:
- $(a,b)\in R$ and $(b,c)\in R$, then $(a,c)\in R$
- Equivalently, you can always "shortcut"

A releation $R\subseteq A\times A$ is an *equivalence relation* if:
- It is relfexive, symmetric, and transitive.
- Example: $A$ (all english words,) $(w_1,w_2) \in R$ if they start with the same letter.

A relation $R\subseteq A\times A$ is a *partial order* if:
- it is reflexive, antisymmetric, and transitive.
- Example. $R=\{(a,b):a,b\text{ are persons and } a \text{ is an ancestor of } b\}$. $\leq$ defined by natural numbers.
- $5 \not< 5$. $5 \leq 5$.


A relation $R\subseteq A\times A$ is a *total order* if:
- It is a partial order and
- $\forall a,b \in A$, exists either $(a,b)\in R$ or $(b,a)\in R$

A set $A\subseteq B$ is *closed* under a relation $R \subseteq ((B\times B)\times B)$ if:
- $a_1, a_2\in A$ and $((a_1,a_2),c)\in R \implies c \in A$
- That is, if $a_1, a_2$ are both in $A$, and $((a_1,a_2),c)$ is in the relation, then $c$ is also in A.
- $N$ is closed under addition.
- $N$ is not closed under subtraction or division.

*** Cardinality
How can we tell if two sets $A$ and $B$ have the same cardinality?
- Calculate $|A|$ and $|B|$ to see if the two numbers are equal.

What if I don't do the calculation?
- Pick up one apple from one basket, then pick one from another.
- If both of them become empty at the same step, they have the same cardinality.
- Create a bijection $f: A\to B$

*** Sets
A set is countable if it is equinemerous with $N$.
- Even numbers of $N$. $f(x)=2x$
- All integers. $f(x)=[\frac{x}{2}]\times(-1)^x$
- Union of two disjoint contable sets
- $N\times N, \text{ where } f(x,y)=\frac{(x+y)(x+y+1)}{2}+x$

**** Uncountable sets
A set is countable if it is equinumerous with $N$.
- There exist uncountable sets, e.g., the rean number between $(0,1)$.
- Suppose there is a bijection:

0. 0.134728...
1. 0.237592...
2. 0.994134...
3. 0.284146...
   ...

You can get an average between two numbers within this uncountable set and get a completely new number.

**** Proof techniques
***** Induction
Claim: Can create exact postage for any amount $\geq 0.08$ dollars using only $3$ cent and $5$ cent stamps.

Inductive case: If we can create exact postage for $x using only 3-cent and 5-cent stamps, we can create exact postage for $x + 0.01 using 3-cent and 5-cent stamps.

Two cases:
1. Exact postage for $x uses at least 5 cent stamp.
2. Exact postage for $x uses no 5-cent stamps.

***** Pigeonhold Principle
$A,B$ are finite sets, with $|A| > |B|$, then there is no one-to-one function from $A$ to $B$.

If you have $n$ pigeonholes, and $> n$ pigeons, and every pigeon is in a pigeonhole, then there must be one hole with $> 1$ pigeon.

Claim: Let $R \subseteq A\times A$ be a relation. If there exists a path in the directed graph representation of $R$, then there exists a path of length at most $|A|$.

- Suppose on the contrary the shortest path has length $\geq |A| + 1$
- In this path $(a_1,a_2,\cdots,a_n)$ there must be some node appears at least twice (pigeonhole principle.)
- $(a_1,a_2,\cdots, a_i, a_{i+1},\cdots, a_j = a_i, a_{j+1},\cdots,a_n)$
- $(a_1,a_2,\cdots,a_i,\cdots, a_{j+1}, \cdots, a_n)$ is shorter.
